on:
  push:
    branches:
      - master
name: 🚀 Deploy to staging master 
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'w2932_cicd'
        server: 'wmsc1-sftp.wedos.net'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_path: '/wwww/'
        args: '-o ConnectTimeout=5'
